cleaned and fixed scripts in .local/bin/ and termux/

diff --git a/.local/bin/passgen b/.local/bin/passgen
--- a/.local/bin/passgen
+++ b/.local/bin/passgen
@@ -1,11 +1,17 @@
 #!/bin/bash
 
-read -p "Enter name of password: " passName
-[ -z "$passName" ] && exit 1
-read -p "Enter length of password: " passLength
-[ -z "$passLength" ] && exit 2
+export PASSWORD_STORE_DIR="$HOME/files/Passwords/store"
+passName=$1   # First Argument is name of password
+passLength=$2 # Second Argument is length of password
+[ -z "$passLength" ] && passLength=20
+
+# Check Errors
 [[ ! "$passLength" =~ ^[0-9]+$ ]] &&
-  echo "Error: Expected a Positive Number" &&
-  read -p "Press enter to exit." && exit 3
+  echo "Error: invalid input. expected a number" &&
+  read -p "Press enter to exit." && exit 1
+[ $passLength -le 0 ] &&
+  echo "Error: invalid input. expected a number greater than 0" &&
+  read -p "Press enter to exit." && exit 2
+
+# Generate password
 pass generate -c "$passName" "$passLength"
-echo "" && read -p "Press enter to exit"
